# Generated by Django 5.2.4 on 2025-08-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.CreateModel(
            name='TeamEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_employee_employee', to='employee.employee', verbose_name='Funcionário')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_employee_team', to='team.team', verbose_name='Equipe')),
            ],
            options={
                'verbose_name': 'Funcionário da equipe',
                'verbose_name_plural': 'Funcionários da equipe',
            },
        ),
    ]
