# Generated by Django 5.2.4 on 2025-07-31 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
    ]
